"""Initial schema — all ORM-backed tables (legacy + automated pipeline).

This is the big-bang replacement for the old hand-written `init_schema.sql`.
Rather than re-transcribing every column as `op.create_table(...)` (risking a
drift from the ORM models), this revision creates/drops tables straight from
`Base.metadata`, which is the single source of truth going forward. Future
schema changes should still be added as normal autogenerated revisions.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-01

"""
from typing import Sequence, Union

from alembic import op

from iso_robot.models import Base

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
