"""issues: denormalize source_document_id and origin

Revision ID: 7f4d85351769
Revises: c75d08a605e5
Create Date: 2026-07-03 17:34:19.940954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4d85351769'
down_revision: Union[str, Sequence[str], None] = 'c75d08a605e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('source_document_id', sa.String(length=64), nullable=True))
    op.add_column('issues', sa.Column('origin', sa.String(length=255), nullable=True))
    op.create_index('idx_issues_org_origin', 'issues', ['client_org_id', 'origin'], unique=False)
    op.create_index('idx_issues_source_doc', 'issues', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_issues_source_doc', table_name='issues')
    op.drop_index('idx_issues_org_origin', table_name='issues')
    op.drop_column('issues', 'origin')
    op.drop_column('issues', 'source_document_id')
    # ### end Alembic commands ###
