"""baseline schema

Revision ID: c75d08a605e5
Revises: 
Create Date: 2026-07-02 15:04:06.064840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75d08a605e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('request_timestamp', sa.String(length=32), nullable=False),
    sa.Column('completion_timestamp', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('input_metadata_json', sa.Text(), nullable=False),
    sa.Column('output_metadata_json', sa.Text(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_audit_log'))
    )
    op.create_index('idx_audit_log_org', 'api_audit_log', ['client_org_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'api_audit_log', ['request_timestamp'], unique=False)
    op.create_table('candidate_risks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issue_ids_json', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_risks'))
    )
    op.create_table('client_organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_client_organizations_slug'))
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=450), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('sha256', name=op.f('uq_documents_sha256'))
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_org', 'documents', ['client_org_id'], unique=False)
    op.create_index('idx_documents_path', 'documents', ['path'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('risk_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('risk_domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_library'))
    )
    op.create_table('risk_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_sources'))
    )
    op.create_table('business_demography',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sub_industry', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.String(length=255), nullable=True),
    sa.Column('annual_revenue', sa.String(length=255), nullable=True),
    sa.Column('headquarters_country', sa.String(length=255), nullable=True),
    sa.Column('headquarters_city', sa.String(length=255), nullable=True),
    sa.Column('ownership_type', sa.String(length=255), nullable=True),
    sa.Column('regulatory_region', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('functions_json', sa.Text(), nullable=False),
    sa.Column('function_catalog', sa.Text(), nullable=False),
    sa.Column('employee_hierarchy', sa.Text(), nullable=False),
    sa.Column('risk_assignment_rules', sa.Text(), nullable=False),
    sa.Column('locations_json', sa.Text(), nullable=False),
    sa.Column('processes_json', sa.Text(), nullable=False),
    sa.Column('regulatory_frameworks_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_business_demography_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_demography')),
    sa.UniqueConstraint('client_org_id', name=op.f('uq_business_demography_client_org_id'))
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('catalog_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('catalog_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_catalog_items_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_items'))
    )
    op.create_index('idx_catalog_items_catalog', 'catalog_items', ['catalog_id'], unique=False)
    op.create_index('idx_catalog_items_org_dim', 'catalog_items', ['client_org_id', 'dimension'], unique=False)
    op.create_table('control_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('document_path', sa.String(length=1024), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('document_category', sa.String(length=255), nullable=True),
    sa.Column('document_version', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_control_documents_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_documents'))
    )
    op.create_index('idx_control_documents_org', 'control_documents', ['client_org_id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('control_text', sa.Text(), nullable=True),
    sa.Column('section_ref', sa.String(length=255), nullable=True),
    sa.Column('framework', sa.String(length=255), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_controls_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controls'))
    )
    op.create_index('idx_controls_document_id', 'controls', ['document_id'], unique=False)
    op.create_index('idx_controls_org', 'controls', ['client_org_id'], unique=False)
    op.create_table('folder_mapping',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('folder_type', sa.String(length=255), nullable=False),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_folder_mapping_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folder_mapping'))
    )
    op.create_index('idx_folder_mapping_org', 'folder_mapping', ['client_org_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('risk_source_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('region_hint', sa.String(length=255), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['risk_source_id'], ['risk_sources.id'], name=op.f('fk_issues_risk_source_id_risk_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_index('idx_issues_org', 'issues', ['client_org_id'], unique=False)
    op.create_index('idx_issues_risk_source_id', 'issues', ['risk_source_id'], unique=False)
    op.create_table('org_hierarchy_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_status', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_org_hierarchy_snapshots_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_hierarchy_snapshots'))
    )
    op.create_index('idx_hierarchy_snapshots_org', 'org_hierarchy_snapshots', ['client_org_id'], unique=False)
    op.create_table('risk_discovery_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_risk_id', sa.String(length=64), nullable=True),
    sa.Column('library_risk_id', sa.String(length=64), nullable=True),
    sa.Column('match_status', sa.String(length=255), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('bm25_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_risk_id'], ['candidate_risks.id'], name=op.f('fk_risk_discovery_results_candidate_risk_id_candidate_risks')),
    sa.ForeignKeyConstraint(['library_risk_id'], ['risk_library.id'], name=op.f('fk_risk_discovery_results_library_risk_id_risk_library')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_discovery_results'))
    )
    op.create_index('idx_risk_discovery_candidate', 'risk_discovery_results', ['candidate_risk_id'], unique=False)
    op.create_table('tenant_mapping',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_tenant_mapping_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_mapping')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_mapping_tenant_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_users_client_org_id_client_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_org', 'users', ['client_org_id'], unique=False)
    op.create_table('issue_classifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('classification_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_classifications_issue_id_issues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_classifications'))
    )
    op.create_index('idx_issue_classifications_issue_id', 'issue_classifications', ['issue_id'], unique=False)
    op.create_table('issue_controls',
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], name=op.f('fk_issue_controls_control_id_controls')),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_controls_issue_id_issues')),
    sa.PrimaryKeyConstraint('issue_id', 'control_id', name=op.f('pk_issue_controls'))
    )
    op.create_index('idx_issue_controls_issue', 'issue_controls', ['issue_id'], unique=False)
    op.create_table('issue_scores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_rating', sa.String(length=255), nullable=True),
    sa.Column('likelihood_score', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('velocity_score', sa.Integer(), nullable=True),
    sa.Column('mapped_functions_json', sa.Text(), nullable=False),
    sa.Column('mapped_locations_json', sa.Text(), nullable=False),
    sa.Column('mapped_processes_json', sa.Text(), nullable=False),
    sa.Column('recommended_risk_title', sa.String(length=512), nullable=True),
    sa.Column('scoring_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_scores_issue_id_issues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_scores'))
    )
    op.create_index('idx_issue_scores_issue', 'issue_scores', ['issue_id'], unique=False)
    op.create_index('idx_issue_scores_org', 'issue_scores', ['client_org_id'], unique=False)
    op.create_table('org_hierarchy_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('function', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('management_level', sa.String(length=255), nullable=True),
    sa.Column('manager_user_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('ownership_roles_json', sa.Text(), nullable=False),
    sa.Column('owned_process_ids_json', sa.Text(), nullable=False),
    sa.Column('owned_kpi_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['org_hierarchy_snapshots.id'], name=op.f('fk_org_hierarchy_users_snapshot_id_org_hierarchy_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_hierarchy_users'))
    )
    op.create_index('idx_hierarchy_users_org', 'org_hierarchy_users', ['client_org_id'], unique=False)
    op.create_index('idx_hierarchy_users_snapshot', 'org_hierarchy_users', ['snapshot_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('risk_type', sa.String(length=255), nullable=True),
    sa.Column('likelihood', sa.String(length=255), nullable=True),
    sa.Column('consequence', sa.String(length=255), nullable=True),
    sa.Column('velocity', sa.String(length=255), nullable=True),
    sa.Column('inherent_risk', sa.String(length=255), nullable=True),
    sa.Column('overall_control_effectiveness', sa.String(length=255), nullable=True),
    sa.Column('residual_risk', sa.String(length=255), nullable=True),
    sa.Column('risk_response', sa.Text(), nullable=True),
    sa.Column('assessment_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_risk_assessments_issue_id_issues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index('idx_risk_assessments_issue', 'risk_assessments', ['issue_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=True),
    sa.Column('risk_title', sa.String(length=512), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=True),
    sa.Column('risk_rating', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('mapped_controls_json', sa.Text(), nullable=False),
    sa.Column('mapped_functions_json', sa.Text(), nullable=False),
    sa.Column('mapped_locations_json', sa.Text(), nullable=False),
    sa.Column('mapped_processes_json', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('process_tags_json', sa.Text(), nullable=False),
    sa.Column('function_tags_json', sa.Text(), nullable=False),
    sa.Column('department_tags_json', sa.Text(), nullable=False),
    sa.Column('kpi_tags_json', sa.Text(), nullable=False),
    sa.Column('region_tags_json', sa.Text(), nullable=False),
    sa.Column('control_family_tags_json', sa.Text(), nullable=False),
    sa.Column('tag_status', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('accountable_user_id', sa.String(length=64), nullable=True),
    sa.Column('owner_assignment_status', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_risks_client_org_id_client_organizations')),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_risks_issue_id_issues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index('idx_risks_org', 'risks', ['client_org_id'], unique=False)
    op.create_table('risk_assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('risk_id', sa.String(length=64), nullable=False),
    sa.Column('recommended_owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('recommended_owner_json', sa.Text(), nullable=False),
    sa.Column('alternate_owners_json', sa.Text(), nullable=False),
    sa.Column('accountable_user_id', sa.String(length=64), nullable=True),
    sa.Column('assignment_type', sa.String(length=255), nullable=True),
    sa.Column('assignment_status', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('matched_on_json', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('hierarchy_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('run_job_id', sa.String(length=64), nullable=True),
    sa.Column('auto_applied', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_risk_assignments_client_org_id_client_organizations')),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_risk_assignments_risk_id_risks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assignments'))
    )
    op.create_index('idx_risk_assignments_org', 'risk_assignments', ['client_org_id'], unique=False)
    op.create_index('idx_risk_assignments_risk', 'risk_assignments', ['risk_id'], unique=False)
    op.create_index('idx_risk_assignments_status', 'risk_assignments', ['assignment_status'], unique=False)
    op.create_table('risk_tags',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_org_id', sa.String(length=64), nullable=False),
    sa.Column('risk_id', sa.String(length=64), nullable=False),
    sa.Column('process_tags_json', sa.Text(), nullable=False),
    sa.Column('function_tags_json', sa.Text(), nullable=False),
    sa.Column('department_tags_json', sa.Text(), nullable=False),
    sa.Column('kpi_tags_json', sa.Text(), nullable=False),
    sa.Column('region_tags_json', sa.Text(), nullable=False),
    sa.Column('control_family_tags_json', sa.Text(), nullable=False),
    sa.Column('tag_status', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('catalog_version', sa.String(length=255), nullable=True),
    sa.Column('run_job_id', sa.String(length=64), nullable=True),
    sa.Column('auto_applied', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_org_id'], ['client_organizations.id'], name=op.f('fk_risk_tags_client_org_id_client_organizations')),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_risk_tags_risk_id_risks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_tags'))
    )
    op.create_index('idx_risk_tags_org', 'risk_tags', ['client_org_id'], unique=False)
    op.create_index('idx_risk_tags_risk', 'risk_tags', ['risk_id'], unique=False)
    op.create_index('idx_risk_tags_status', 'risk_tags', ['tag_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_risk_tags_status', table_name='risk_tags')
    op.drop_index('idx_risk_tags_risk', table_name='risk_tags')
    op.drop_index('idx_risk_tags_org', table_name='risk_tags')
    op.drop_table('risk_tags')
    op.drop_index('idx_risk_assignments_status', table_name='risk_assignments')
    op.drop_index('idx_risk_assignments_risk', table_name='risk_assignments')
    op.drop_index('idx_risk_assignments_org', table_name='risk_assignments')
    op.drop_table('risk_assignments')
    op.drop_index('idx_risks_org', table_name='risks')
    op.drop_table('risks')
    op.drop_index('idx_risk_assessments_issue', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('idx_hierarchy_users_snapshot', table_name='org_hierarchy_users')
    op.drop_index('idx_hierarchy_users_org', table_name='org_hierarchy_users')
    op.drop_table('org_hierarchy_users')
    op.drop_index('idx_issue_scores_org', table_name='issue_scores')
    op.drop_index('idx_issue_scores_issue', table_name='issue_scores')
    op.drop_table('issue_scores')
    op.drop_index('idx_issue_controls_issue', table_name='issue_controls')
    op.drop_table('issue_controls')
    op.drop_index('idx_issue_classifications_issue_id', table_name='issue_classifications')
    op.drop_table('issue_classifications')
    op.drop_index('idx_users_org', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_mapping')
    op.drop_index('idx_risk_discovery_candidate', table_name='risk_discovery_results')
    op.drop_table('risk_discovery_results')
    op.drop_index('idx_hierarchy_snapshots_org', table_name='org_hierarchy_snapshots')
    op.drop_table('org_hierarchy_snapshots')
    op.drop_index('idx_issues_risk_source_id', table_name='issues')
    op.drop_index('idx_issues_org', table_name='issues')
    op.drop_table('issues')
    op.drop_index('idx_folder_mapping_org', table_name='folder_mapping')
    op.drop_table('folder_mapping')
    op.drop_index('idx_controls_org', table_name='controls')
    op.drop_index('idx_controls_document_id', table_name='controls')
    op.drop_table('controls')
    op.drop_index('idx_control_documents_org', table_name='control_documents')
    op.drop_table('control_documents')
    op.drop_index('idx_catalog_items_org_dim', table_name='catalog_items')
    op.drop_index('idx_catalog_items_catalog', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('business_demography')
    op.drop_table('risk_sources')
    op.drop_table('risk_library')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_documents_path', table_name='documents')
    op.drop_index('idx_documents_org', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_table('client_organizations')
    op.drop_table('candidate_risks')
    op.drop_index('idx_audit_log_timestamp', table_name='api_audit_log')
    op.drop_index('idx_audit_log_org', table_name='api_audit_log')
    op.drop_table('api_audit_log')
    # ### end Alembic commands ###
