"""add confidence and reasoning fields

Revision ID: d90cb48d1568
Revises: 0002_pipeline_batching
Create Date: 2026-07-13 15:23:25.954930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd90cb48d1568'
down_revision: Union[str, None] = '0002_pipeline_batching'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_risks', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('controls', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('issues', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'reasoning')
    op.drop_column('issues', 'confidence')
    op.drop_column('controls', 'reasoning')
    op.drop_column('controls', 'confidence')
    op.drop_column('candidate_risks', 'reasoning')
    # ### end Alembic commands ###
